 #include <iostream.h>
 #include <conio.h>
 #include <string.h>
 #include <stdio.h>


main()
{
clrscr();
/*char str[20];
char str1[20];

cout<<"Enter your name"<<endl;
//cin>>str;
gets(str);

cout<<"enter one more string"<<endl;
gets(str1);

cout<<endl<<"You have entered a name"<<str<<endl;

int len=strlen(str);
cout<<"The lenght of the string"<<len<<endl;


cout<<"Revserse of the string"<<strrev(str)<<endl;
// puts(str);


strcat(str,str1);
cout<<"concatenation of the two string ="<<str<<endl;
*/

cout<<"enter a character"<<endl;
char ch;

ch=getche();

cout<<endl<<"you have entered a character"<<ch;

cout<<endl<<"Enter a key to exit"<<endl;
getch();

}


